config/routes.rb
Rails.application.routes.draw do
  get 'containers/index'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
resources :containers, only: [:index, :show, :new, :create] do
  resources :bookings, only: [:create]
end
resources :bookings, only: [:index] do
  member do
    patch "accept"
    patch "decline"
  end
  collection do
    get :completed
    get :rejected
    get :purchases
    get :pending
    get :active
  end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :container
  belongs_to :user


end

app/models/container.rb
class Container < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo


  validates :name, presence: true, uniqueness: {scope: :user_id, message: "You have already created a container with this name"}
  validates :detail, presence: true, length: { minimum: 15 }
  validates :height,:width,:length, presence: true, format: { with: /\A\d+\.?\d{0,2}\z/, message: "enter to Maximum of 2 decimal places e.g. 1.25"}, numericality: {greater_than_or_equal_to: 1}
  validates :maximum_weight,:empty_weight, presence: true, format: { with: /\A\d+\.?\d{0,2}\z/, message: "enter to Maximum of 2 decimal places e.g. 1.25"}, numericality: {greater_than_or_equal_to: 1}
  validates :daily_price, presence: true, format: { with: /\A\d+\.?\d{0,2}\z/, message: "enter to Maximum of 2 decimal places e.g. 1.25"}, numericality: {greater_than_or_equal_to: 1}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :container_lookup, only: %i[create]

def index
  @my_pending = Booking.where(user_id: current_user,accept: false, decline: false).order(:id)
  @my_bookings = Booking.where(user_id: current_user).where("date_to > ?", DateTime.now).order(date_from: :desc)

end

def create

    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.container = @container
    @booking.price = calculate_price
    @booking.accept = false
    @booking.decline = false
    if @booking.save
      redirect_to container_path(@container)
    else
      render 'containers/show', status: :unprocessable_entity
    end
end

def accept
  @booking = Booking.find(params[:id])

  if date_clash(@booking)==true
    redirect_to pending_bookings_path, status: :see_other
  else
    @booking.accept=true
    @booking.save
    redirect_to pending_bookings_path, status: :see_other
  end
end

def decline
  @booking = Booking.find(params[:id])
  @booking.decline =true
  @booking.save
  redirect_to pending_bookings_path, status: :see_other
end


def pending
  @containers = Container.where(user_id: current_user)
  @sales_pending = []
  @containers.each do |container|
    if container.bookings.all.empty?
    else
    @sales_pending << container.bookings.where(accept: false, decline: false).order(id: :desc)
    end
  end
end

def completed
  @containers = Container.where(user_id: current_user)
  @sales_completed = []
  @containers.each do |container|
    if container.bookings.all.empty?
    else
    @sales_completed << container.bookings.where(accept: true).where("date_to < ?", DateTime.now).order(date_from: :desc)
    end
  end
end

def active
  @containers = Container.where(user_id: current_user)
  @sales_active = []
  @containers.each do |container|
    if container.bookings.all.empty?
    else
    @sales_active << container.bookings.where(accept: true).where("date_to > ?", DateTime.now).order(date_from: :desc)
    end
  end
end


def rejected
  @containers = Container.where(user_id: current_user)
  @sales_rejected = []
  @containers.each do |container|
    if container.bookings.all.empty?
    else
    @sales_rejected << container.bookings.where(decline: true).order(date_from: :desc)
    end
  end
end




private
  def booking_params
    params.require(:booking).permit(:comment, :date_from, :date_to)
  end



  def container_lookup
    @container = Container.find(params[:container_id])
  end

  def calculate_price
    @price = calculate_days * @container.daily_price
  end

  def calculate_days
    #placeholder calculation - need to calculate based on number of days
    @days = @booking.date_to - @booking.date_from
    @days = @days.to_i
    @days = @days + 1
  end

  def date_clash(booking)
    clashes = Booking.where("date_to > ?", DateTime.now)
    clashes = clashes.where(accept: true)
    result = false
      clashes.each do |clash|
        break if result==true
        if booking.date_from > clash.date_from && booking.date_from < clash.date_to
          result = true
        elsif booking.date_to > clash.date_from && booking.date_to < clash.date_to
          result = true
        elsif booking.date_from < clash.date_from && booking.date_to > clash.date_to
          result = true
        else
          result = false
        end
        end
      return result
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_user, only: %i[new create]
  skip_before_action :authenticate_user!, only: :index
  def index
    @containers = Container.all
  end
  def new
    @container = Container.new
  end

  def create
    @container = Container.new(container_params)
    @container.user = @user
    if @container.save
      redirect_to containers_path
    else
      render :new, status: :unprocessable_entity
  end
end

def show
  @container = Container.find(params[:id])
  @booking = Booking.new
  @bookings = @container.bookings.where(user_id: current_user).order(id: :desc)
end

private

def container_params
  params.require(:container).permit(:name, :detail, :width, :height, :length, :maximum_weight, :empty_weight, :daily_price, :photo)
end

def set_user
  @user = current_user
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/active.html.erb
<div class="container">
<h1>Active Orders</h2>
<%= render "shared/orderNavigation"%>
<% if @sales_active.empty?%>
  <h1>You have no Active orders</h1>
<% else %>
  <% @sales_active.each do |my_sale| %>
      <% my_sale.each do |sale| %>
      <div class="card-booking-history border p-4 m-4" style="background-color:#ddffdd;">

      <p>Your Container Reference: <%= sale.container.name %></p>
      <p>Customer Contact: <%= sale.user.email %></p>
      <p>Customer Comments: <%= sale.comment %></p>
      <p>Order ID: <%= sale.id %></p>
      <p>Rental Start Date: <%= sale.date_from %></p>
      <p>Rental End Date:<%= sale.date_to %></p>
      <p>Total: £<%= sale.price %></p>
      <div class="d-flex flex-row justify-content-around">
      </div>
      </div>
      <% end %>
  <% end %>
<% end %>
</div>

app/views/bookings/completed.html.erb
<div class="container">
<h1>Completed</h2>
<%= render "shared/orderNavigation"%>
<% if @sales_completed.empty?%>
  <h1>You have no Completed orders</h1>
<% else %>
  <% @sales_completed.each do |my_sale| %>
      <% my_sale.each do |sale| %>
      <div class="card-booking-history border p-4 m-4" style="background-color:#ddffdd;">

      <p>Your Container Reference: <%= sale.container.name %></p>
      <p>Customer Contact: <%= sale.user.email %></p>
      <p>Customer Comments: <%= sale.comment %></p>
      <p>Order ID: <%= sale.id %></p>
      <p>Rental Start Date: <%= sale.date_from %></p>
      <p>Rental End Date:<%= sale.date_to %></p>
      <p>Total: £<%= sale.price %></p>
      <div class="d-flex flex-row justify-content-around">
      </div>
      </div>
      <% end %>
  <% end %>
<% end %>
</div>

app/views/bookings/index.html.erb
<div class="container">
<h1>My Rentals</h1>

 <% @my_bookings.each do |my_booking| %>

    <% if my_booking.decline == true %>
      <div class="card order-form m-3" style="background-color:#ffdddd";>
      <h2>DECLINED</h2>
      <div class="d-flex flex-row justify-content-between m-3">
    <% elsif my_booking.accept == true %>
      <div class="card order-form m-3" style="background-color:#ddffdd;">
      <h2>ACCEPTED!</h2>
      <div class="d-flex flex-row justify-content-between m-3">
    <% else %>
      <h2>  status: pending <br></h2>
    <% end %>
      <div class="m-3">
        <%= cl_image_tag(my_booking.container.photo.key, height: 300, width: 400, crop: :fill) %>
      </div>
      <div class="card-body">
        <h2>Container: <%= my_booking.container.name %></h2>
        <p>Contact Seller: <%= my_booking.container.user.email %></p>
            <%= my_booking.comment %><br>
            Price: <%= my_booking.price %><br>
            Rental Start Date: <%= my_booking.date_from %><br>
            Rental End Date: <%= my_booking.date_to %><br>
            <%= link_to "Order Again?", container_path(my_booking.container), class: "btn btn-primary"%>
      </div>
    </div>
  </div>
 <% end %>
</div>

app/views/bookings/pending.html.erb
<div class="container">
<h1>Pending Orders</h2>
<h2>Don't leave your customers hanging, approve or decline the orders below</h3>
<%= render "shared/orderNavigation"%>


<% if @sales_pending.empty?%>
  <h1>You have no pending orders</h1>
<% else %>
  <% @sales_pending.each do |my_sale| %>
      <% my_sale.each do |sale| %>
      <div class="card-booking-history border p-4 m-4 #ddffff">

      <p>Your Container Reference: <%= sale.container.name %></p>
      <p>Customer Contact: <%= sale.user.email %></p>
      <p>Customer Comments: <%= sale.comment %></p>
      <p>Rental Start Date: <%= sale.date_from %></p>
      <p>Rental End Date:<%= sale.date_to %></p>
      <p>Total: £<%= sale.price %></p>
      <div class="d-flex flex-row justify-content-around">
      <%= button_to "Accept", accept_booking_path(sale), method: :patch, class: "btn btn-success" %>
      <%= button_to "Decline", decline_booking_path(sale), method: :patch, class: "btn btn-danger" %>
      </div>
      </div>
      <% end %>
  <% end %>
<% end %>
</div>

app/views/bookings/rejected.html.erb
<div class="container">
<h1>Rejected Orders</h2>
<%= render "shared/orderNavigation"%>

<% if @sales_rejected.empty?%>
  <h1>You have no rejected orders</h1>
<% else %>
  <% @sales_rejected.each do |my_sale| %>
      <% my_sale.each do |sale| %>
      <div class="card-booking-history border p-4 m-4" style="background-color:#ffdddd;">

      <p>Your Container Reference: <%= sale.container.name %></p>
      <p>Customer Contact: <%= sale.user.email %></p>
      <p>Customer Comments: <%= sale.comment %></p>
      <p>Order ID: <%= sale.id %></p>
      <p>Rental Start Date: <%= sale.date_from %></p>
      <p>Rental End Date:<%= sale.date_to %></p>
      <p>Total: £<%= sale.price %></p>
      <div class="d-flex flex-row justify-content-around">
      </div>
      </div>
      <% end %>
  <% end %>
<% end %>
</div>

app/views/containers/index.html.erb
<h1>Containers</h1>



<div class="container">
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
    <li class="breadcrumb-item active" aria-current="page">Containers</li>
  </ol>
</nav>
<div class="cards-containers">
  <% @containers.each do |container| %>
    <div class="card card-container">
      <%= cl_image_tag(container.photo.key, height: 300, width: 400, crop: :fill) %>
        <div class="card-body">
        <h5 class="card-title"><%= container.name %></h5>
           <p class="card-text"><%= container.detail %></p>
           <p class="card-text">Daily Rental Price: £<%= container.daily_price %></p>
           <p class="card-text">HxWxL: <%= container.width %> x <%= container.height %> x <%= container.length %></p>
           <p class="card-text">Empty Weight: <%= container.empty_weight %></p>
           <p class="card-text">Maximum Cargo Weight: <%= container.maximum_weight %></p>
           <%=link_to "Show Container", container_path(container) %>
          </div>
    </div>

  <% end %>
</div>
</div>

app/views/containers/new.html.erb
<div class="container-lg border form mt-4">
<h1 class="mt-4">Create A Container</h1>
    <%= simple_form_for @container do |f|%>
    <%= f.input :name %>
    <%= f.input :detail %>
    <%= f.input :height %>
    <%= f.input :width %>
    <%= f.input :length %>
    <%= f.input :maximum_weight %>
    <%= f.input :empty_weight %>
    <%= f.input :daily_price %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn btn-primary mt-4 mb-4" %>
    <% end %>
</div>
</div>

app/views/containers/show.html.erb
<div class="container">
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Home", root_path%></li>
    <li class="breadcrumb-item"><%= link_to "Containers", containers_path%></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @container.name %></li>
  </ol>
</nav>

<div class="d-flex flex-row justify-content-evenly">

  <div>
    <%= cl_image_tag(@container.photo.key, height: 300, width: 400, crop: :fill) %>
  </div>
  <div class= "card form " style="width:100%;">
        <div class="card-body">
        <h2><%= @container.name %></h2>
        <p class="card-text">Daily Price: £<%= @container.daily_price %><br>
        <p class="card-text">HxWxL = <%= @container.height %>x<%= @container.width %>x<%= @container.length %><br>
        <p class="card-text">Container weight: <%= @container.empty_weight %></p>
        <p class="card-text">Max Cargo Weight: <%= @container.maximum_weight %></p>
        <p class="card-text"><%= @container.detail %></p>
    </div>
  </div>
</div>
  <div>
  <br>
  <div class="border order-form mt-4 p-3">
  <h2>Rent Container</h2>
    <%= simple_form_for [@container, @booking] do |f| %>
      <%= f.input :comment %>
      <%= f.input :date_from,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :date_to,
            as: :string,
            input_html: { data: { controller: "datepicker" }, },
            class: "m-4" %>
      <%= f.button :submit, "Submit", class: "btn btn-primary m-3"%>
    <% end %>
</div>
</div>

<br>
<br>
<br>
<h2>Your Rental History</h2>

<% if @bookings.count == 0 %>
  <p>you have not rented this container before</p>
<% else %>
` <% @bookings.each do |booking| %>
<br>
    <% if booking.decline == true %>
      <div class="card-booking-history border p-4" style="background-color:#ffdddd;">
       <h2> Order Declined<br></h2>
       <h3> Contact the seller for more details</h3>
        <% elsif booking.accept == true %>
        <div class="card-booking-history border p-4" style="background-color:#ddffdd;">
         <h2>Order Accepted!<br></h2>
        <% else %>
        <div class="card-booking-history border p-4" style="background-color:#ddffff;">
       <h2>  The seller is checking over your order and will update shortly <br></h2>
        <% end %>


      <p> Price: £<%= booking.price %></p>
      <p> Collection Date: <%= booking.date_from %></p>
      <p> Return Date: <%= booking.date_to %></p>
      <p style="font-size:18px;">Your Comments: <%= booking.comment %></p>

    </div>
  <% end %>
    <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsContainer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">


  </head>

  <body>
    <%= render "shared/navbar" %>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homepage-container" style="width: 100%">
  <div class="banner" style="width: 100%; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.shutterstock.com/image-photo/aerial-view-large-industrial-container-600nw-2509185793.jpg);">
    <div class="container">
      <h1>Welcome to Containers R Us</h1>
      <p>Book your shipping containers with ease.</p>
      <%= link_to 'View Available Containers', containers_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-ship"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Containers", containers_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown mt-2">
          <a href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-decoration: none; color: #000000A6;">
           My Account
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Rentals", bookings_path, class: "dropdown-item" %>
              <%= link_to "My Sales", pending_bookings_path, class: "dropdown-item" %>
              <%= link_to "List Container", new_container_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_orderNavigation.html.erb
<div class="flex-d">
<%= link_to "Pending Approval", pending_bookings_path, class: "btn btn-primary" %>
<%= link_to "Active", active_bookings_path, class: "btn btn-primary" %>
<%= link_to "Completed", completed_bookings_path, class: "btn btn-primary" %>
<%= link_to "Rejected", rejected_bookings_path, class: "btn btn-primary" %>
</div>